- hosts: postgres
  become: sudo
  vars:
    etcd_token: "postgres"
    patroni_scope: "postgres"
    patroni_namespace: "db"
    patroni_hosts:
    - { hn: host11, ip: 10.0.0.11 }
    - { hn: host12, ip: 10.0.0.12 }
    - { hn: host13, ip: 10.0.0.13 }
    etcd_hosts:
    - { hn: host11, ip: 10.0.0.11 }
    - { hn: host12, ip: 10.0.0.12 }
    - { hn: host13, ip: 10.0.0.13 }
  tasks:
    - name: Postgres kur
      script: scripts/install_pg.sh
    - name: copy files
      template: src={{item.src}} dest={{item.dest}} mode={{item.mode}}
      with_items:
        - { src: 'templates/etcd.j2', dest: '/etc/default/etcd', mode: '644' }
        - { src: 'templates/patroni.j2', dest: '/etc/patroni.yml', mode: '644' }
        - { src: 'templates/patroni.service', dest: '/lib/systemd/system/patroni.service', mode: '644' }
      sudo: yes
    - name: restart etcd and patroni
      script: scripts/restart.sh

- hosts: pgbouncer
  become: sudo
  vars:
    etcd_token: "postgres"
    patroni_scope: "postgres"
    patroni_namespace: "db"
    etcd_hosts:
    - { hn: host11, ip: 10.0.0.11 }
    - { hn: host12, ip: 10.0.0.12 }
    - { hn: host13, ip: 10.0.0.13 }
  tasks:
    - name: install packages
      shell: sudo apt update && sudo apt install pgbouncer -y
    - name: create dirs
      shell: sudo mkdir -p /etc/confd/conf.d && sudo mkdir -p /etc/confd/templates
    - name: Download confd
      script: scripts/download_confd.sh
    - name: copy template files
      template: src={{item.src}} dest={{item.dest}} mode={{item.mode}}
      with_items:
        - { src: 'pgbouncer/pg_hba.txt', dest: '/etc/pgbouncer/pg_hba.txt', mode: '644' }
        - { src: 'pgbouncer/userlist.txt', dest: '/etc/pgbouncer/userlist.txt', mode: '644' }
        - { src: 'confd/conf.d/pgbouncer.toml.j2', dest: '/etc/confd/conf.d/pgbouncer.toml', mode: '644' }
        - { src: 'confd/confd.toml.j2', dest: '/etc/confd/confd.toml', mode: '644' }
        - { src: 'confd/confd.service', dest: '/lib/systemd/system/confd.service', mode: '644' }
      sudo: yes
    - name: copy non template files
      copy: src={{item.src}} dest={{item.dest}} mode={{item.mode}}
      with_items:
        - { src: 'confd/templates/pgbouncer.tmpl', dest: '/etc/confd/templates/pgbouncer.tmpl', mode: '644' }
      sudo: yes
    - name: service scripts
      script: scripts/confd_scripts.sh
