#backend = "etcd"
#client_cert = "/etc/confd/ssl/client.crt"
#client_key = "/etc/confd/ssl/client.key"
#confdir = "/etc/confd"
#log-level = "debug"
interval = 10
nodes = [
  "http://10.0.0.11:2379",
  "http://10.0.0.12:2379",
  "http://10.0.0.13:2379"
]
#noop = false
prefix = "/db/postgres"
#scheme = "https"
#srv_domain = "etcd.example.com"
